name: advostarter-d-8
recipe: pantheon
config:
  framework: drupal
  env: dev
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  backstopserver:
    type: 'node:10'
    overrides:
      image: 'backstopjs/backstopjs:4.0.6'
tooling:
  push: disabled
  backstop:
    service: backstopserver
    description: |
      Run BackstopJS for visual regression testing.  E.g.
        lando backstop test
      See tests/backstop/README.md for more info.
    cmd:
      - cd /app/tests/backstop && backstop --config=/app/tests/backstop/backstop-local.json
  drush:
    service: appserver
    cmd: drush --root=/app/web
  wave:
    service: appserver
    description: |
      Process a CSV file of URLs through WAVE.  E.g.
        lando wave my.csv Rk3fKE231077
      1. You might generate the CSV file with Screaming Frog.
      2. If you want to keep things _real_ simple, just create a blank file and
         put one URL per line.
      3. The CSV file must exist within the project codebase.
      4. You don't _really_ need Lando to run this.  You can call the script
         directly:
          ./tests/wave/wave-csv-test ~/path/to/some.csv Rk3fKE231077

    cmd:
      - /app/tests/wave/wave-csv-test
